apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: starter-app
      labels:
        app: starter-app
        app.kubernetes.io/component: starter-app
        app.kubernetes.io/instance: starter-app
        app.kubernetes.io/name: starter-app
        app.kubernetes.io/part-of: starter-app
        app.openshift.io/runtime: ruby
        app.openshift.io/runtime-version: 3.0-ubi7
    spec:
      source:
        type: Git
        git:
          uri: 'https://github.com/txsvc/starter-app.git'
        contextDir: /
      
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'ruby:3.0-ubi7'
          env:
            - name: BUNDLE_REBUILD
              valueFrom:
                configMapKeyRef:
                  name: starter-app-build-config-map
                  key: bundle-rebuild
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: starter-app-secrets
                  key: rails-master-key
      
      output:
        to:
          kind: ImageStreamTag
          name: 'starter-app:latest'
      
      triggers:
        - type: Generic
          generic:
            secretReference:
              name: starter-app-webhook-secrets
        - type: GitHub
          github:
            secretReference:
              name: starter-app-webhook-secrets
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
      
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      postCommit: {}
      runPolicy: Serial

  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: starter-app
      labels:
        app: starter-app
        app.kubernetes.io/component: starter-app
        app.kubernetes.io/instance: starter-app
        app.kubernetes.io/name: starter-app
        app.openshift.io/runtime: ruby
        app.openshift.io/runtime-version: 3.0-ubi7
    spec:
      lookupPolicy:
        local: false