kind: Secret
apiVersion: v1
metadata:
  name: starter-app-secrets
type: Opaque
stringData:
  rails-master-key: xyz
  application-password: xyz
  application-user: xyz
  database-password: xyz
  database-user: xyz
# other secret key/value pairs ...
